image: alpine:latest
services:
  - docker:dind

variables:
  GOPATH: "/go"

stages:
  - build_app
  - build_image

build-app:
  stage: build_app
  artifacts:
    paths:
    - altair

  script:
  # Install Apps
  - apk --no-cache add git openssl openssh-client
  - mkdir -p ~/.ssh
  - echo -e "$CI_SSH_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - git config --global url."git@gitlab.com:".insteadOf "https://gitlab.com/"
  # Install Golang
  - wget https://storage.googleapis.com/golang/go1.12.4.linux-amd64.tar.gz
  - echo "Extracting golang..." && tar -C /usr/local -xzf go1.12.4.linux-amd64.tar.gz
  - mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
  - export PATH=$PATH:/usr/local/go/bin
  - mkdir -p /go/src

  # Symlink
  - ln -s /builds /go/src/gitlab.com

  # Build
  - cd /go/src/gitlab.com/${CI_PROJECT_PATH}/cmd/altair
  - go get -v
  - cd /go/src/gitlab.com/${CI_PROJECT_PATH}
  - go build -o altair ./cmd/altair/main.go

build-image:
  image: docker:latest
  stage: build_image
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t registry.gitlab.com/startail/altair .
  - docker push registry.gitlab.com/startail/altair
