name: CI
on:
  branches:
    - master
jobs:
  build:
    name: build-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Google Container Registry
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.STARTAIL_GCP_SERVICE_ACCOUNT }}
        run: docker login -u _json_key -p "$(echo $GCP_SERVICE_ACCOUNT)" gcr.io
      - name: Build Image
        run: docker build . -t gcr.io/startail-io/altair:latest
      - name: Push Image
        run: docker push gcr.io/startail-io/altair:latest
